/* ###################################################################
**     This component module is generated by Processor Expert. Do not modify it.
**     Filename    : internal_rtc_1.c
**     Project     : byteone_fw_s32
**     Processor   : S32K144_48
**     Component   : rtc
**     Version     : Component SDK_S32K1xx_15, Driver 01.00, CPU db: 3.00.000
**     Repository  : SDK_S32K1xx_15
**     Compiler    : GNU C Compiler
**     Date/Time   : 2025-02-05, 13:56, # CodeGen: 1
**
**     Copyright 1997 - 2015 Freescale Semiconductor, Inc. 
**     Copyright 2016-2017 NXP 
**     All Rights Reserved.
**     
**     THIS SOFTWARE IS PROVIDED BY NXP "AS IS" AND ANY EXPRESSED OR
**     IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
**     OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
**     IN NO EVENT SHALL NXP OR ITS CONTRIBUTORS BE LIABLE FOR ANY DIRECT,
**     INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**     (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
**     SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
**     HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
**     STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING
**     IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF
**     THE POSSIBILITY OF SUCH DAMAGE.
** ###################################################################*/
/*!
** @file internal_rtc_1.c
** @version 01.00
*/         
/*!
**  @addtogroup internal_rtc_1_module internal_rtc_1 module documentation
**  @{
*/         

/*! MODULE internal_rtc_1. */

#include "internal_rtc_1.h"

/**
 * @page misra_violations MISRA-C:2012 violations
 *
 * @section [global]
 * Violates MISRA 2012 Advisory Rule 8.7, External variable could be made static.
 * The external variables will be used in other source files in application code.
 *
 * @section [global]
 * Violates MISRA 2012 Advisory Rule 2.5, global macro not referenced
 * There are global macros defined to be used by the integrator and another one used as include guard.
 */


/*! internal_rtc_1 Fault Callback declaration */
extern void internal_rtc_1_FaultIntCallback0(void * callbackParam);

/*! internal_rtc_1 Alarm Configuration 0 Callback declaration */
extern void internal_rtc_1_AlarmCallback0(void * callbackParam);


/*! internal_rtc_1 configuration structure */
rtc_init_config_t internal_rtc_1_Config0 =
{
    /*! Time compensation interval */
    .compensationInterval       =   0U,
    /*! Time compensation value */
    .compensation               =   0,
    /*! RTC Clock Source is 1KHz LPO */
    .clockSelect                =   RTC_CLK_SRC_LPO_1KHZ,
    /*! RTC Clock Out is disabled */
    .clockOutConfig             =   RTC_CLKOUT_DISABLED,
    /*! Update of the TCE bit is not allowed */
    .updateEnable               =   false,
    /*! Non-supervisor mode write accesses are not supported and generate
     * a bus error.
     */
    .nonSupervisorAccessEnable  =   false
};


/*! internal_rtc_1 Initial Time and Date */
rtc_timedate_t internal_rtc_1_StartTime0 =
{
    /*! Year */
    .year       =   2016U,
    /*! Month */
    .month      =   1U,
    /*! Day */
    .day        =   1U,
    /*! Hour */
    .hour       =   0U,
    /*! Minutes */
    .minutes    =   0U,
    /*! Seconds */
    .seconds    =   0U
};

/*! internal_rtc_1 Register lock configuration 0 */
rtc_register_lock_config_t internal_rtc_1_LockConfig0 =
{
    /*! Do not change the lock state of the Lock Register */
    .lockRegisterLock               =   false,
    /*! Do not change the lock state of the Status Register */
    .statusRegisterLock             =   false,
    /*! Do not change the lock state of the Control Register */
    .controlRegisterLock            =   false,
    /*! Do not change the lock state of the Time Compensation Register */
    .timeCompensationRegisterLock   =   false
};

/*! internal_rtc_1 Fault Interrupt configuration (Time Overflow Interrupt & Time Invalid Interrupt) 0 */
rtc_interrupt_config_t internal_rtc_1_FaultIntConfig0 =
{
    /*! Time Overflow Interrupt is enabled */
    .overflowIntEnable      =   true,
    /*! Time Invalid Interrupt is enabled */
    .timeInvalidIntEnable   =   true,
    /*! General User Callback */
    .rtcCallback            =   internal_rtc_1_FaultIntCallback0,
    /*! General User Callback Parameters */
    .callbackParams         =   NULL
};

/*! internal_rtc_1 Time Seconds Interrupt Configuration 0 */
rtc_seconds_int_config_t internal_rtc_1_SecIntConfig0 =
{
    /*! Time Seconds Interrupt Frequency @ 1 Hz */
    .secondIntConfig               =    RTC_INT_1HZ,
    /*! Time Seconds Interrupt is disabled */
    .secondIntEnable               =    false,
    /*! Time Seconds Interrupt User Callback */
    .rtcSecondsCallback            =    NULL,
    /*! Time Seconds Interrupt User Callback Parameters */
    .secondsCallbackParams         =    NULL
};

/*! internal_rtc_1 Alarm configuration 0 */
rtc_alarm_config_t internal_rtc_1_AlarmConfig0 =
{
    /*! Alarm Date */
    .alarmTime           =
        {
            /*! Year    */
            .year       =   2016U,
            /*! Month   */
            .month      =   1U,
            /*! Day     */
            .day        =   1U,
            /*! Hour    */
            .hour       =   0U,
            /*! Minutes */
            .minutes    =   0U,
            /*! Seconds */
            .seconds    =   0U,
        },
    /*! Alarm repeat interval */
    .repetitionInterval  =      0UL,
    /*! Number of alarm repeats */
    .numberOfRepeats     =      0UL,
    /*! Repeat alarm disabled */
    .repeatForever       =      false,
    /*! Alarm interrupt enabled */
    .alarmIntEnable      =      true,
    /*! Alarm interrupt User Callback */
    .alarmCallback       =      internal_rtc_1_AlarmCallback0,
    /*! Alarm interrupt handler parameters */
    .callbackParams      =      NULL
};

/*! END internal_rtc_1. */
/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.1 [05.21]
**     for the Freescale S32K series of microcontrollers.
**
** ###################################################################
*/

